server:
    port: 80

liquibase:
    context: prod

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: mng
            port: 27017
            database: checkout
    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: checkout

http:
    cache:
        timeToLiveInDays: 31

mightymerce:
    coreUrl: 
    coreUser: 
    corePassword: 

