server:
    port: 8081

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    data:
        mongodb:
            host: localhost
            port: 27017
            database: checkout
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: checkout
        
mightymerce:
    coreUrl: http://localhost:8082/
    coreUser: admin
    corePassword: admin


